### ISSUE TITLE
missing required architecture x86_64 in file /SmartsdkKit.framework/SmartsdkKit (2 slices)

### ISSUE THREAD

**Issue by abeauvois** [ariadnext/IDCHECK.IO_SDK-example-iOS#1]
Hi,
After following installation setup from docs I get a "missing required architecture x86_64" error
Any idea about this issue ?

My env: 
MacOSX Sierra 10.12.5
xcode Version 8.3.2 (8E2002)
smartsdk-IOS-4.1.3-ios-framework

When buildng I'm getting this error:

SmartsdkKit -framework Accelerate -framework AssetsLibrary -framework CoreMedia -framework SmartsdkKit -framework AVFoundation -framework ImageIO -framework CoreMotion -framework SystemConfiguration -lz -liconv -Xlinker -dependency_info -Xlinker /Users/ab/Library/Developer/Xcode/DerivedData/idcheckio-example-gzovchejukjdfwbqwlrealsfcwoa/Build/Intermediates/idcheckio-example.build/Debug-iphonesimulator/idcheckio-example.build/Objects-normal/x86_64/idcheckio-example_dependency_info.dat -o /Users/ab/Library/Developer/Xcode/DerivedData/idcheckio-example-gzovchejukjdfwbqwlrealsfcwoa/Build/Products/Debug-iphonesimulator/idcheckio-example.app/idcheckio-example

ld: warning: ignoring file /Users/ab/Documents/idcheckios/SmartsdkKit.framework/SmartsdkKit, missing required architecture x86_64 in file /Users/ab/Documents/idcheckios/SmartsdkKit.framework/SmartsdkKit (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AXTImageResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_AXTSdkResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_AXTCaptureInterface", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_AXTSdkParams", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by abeauvois** [comment]
Answer: Just compile to physical device (arm).
Explanation: xCode simulators are based on x86 architecture

**Comment by Denjag** [comment]
Hi Alexandre,

Indeed, by default, our SDK doesn't work with Xcode simulator.

If you need, we can give you a version who support the simulator.

Regards

**Comment by abeauvois** [comment]
Hi Denjag, that's fine without the simulator (make sense as it's a hardware feature), just perhaps make this clearer in the docs that even with theses errors it will work on physical device. Could help others. Thx.
